# Generated by Django 2.1.7 on 2019-02-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('invoice', models.IntegerField()),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.IntegerField()),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='selectedorders',
            name='selected_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.SelectedProducts'),
        ),
    ]
