# Generated by Django 2.1.7 on 2019-02-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedorders',
            name='price',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='scrapping_app.SelectedProducts'),
            preserve_default=False,
        ),
    ]
