# Generated by Django 2.1.7 on 2019-02-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0003_auto_20190222_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedorders',
            name='selected_products',
        ),
        migrations.AddField(
            model_name='selectedorders',
            name='order_user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedproducts',
            name='accout_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.Account'),
            preserve_default=False,
        ),
    ]
