# Generated by Django 2.1.7 on 2019-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0004_auto_20190222_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedorders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='selectedproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
