# Generated by Django 2.1.7 on 2019-02-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0006_auto_20190222_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproducts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapping_app.SelectedOrders'),
        ),
    ]
