# Generated by Django 2.1.7 on 2019-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0007_selectedproducts_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedorders',
            name='order_user_id',
        ),
        migrations.RemoveField(
            model_name='selectedorders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='selectedproducts',
            name='accout_id',
        ),
        migrations.RemoveField(
            model_name='selectedproducts',
            name='order',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='SelectedOrders',
        ),
        migrations.DeleteModel(
            name='SelectedProducts',
        ),
    ]
