# Generated by Django 2.1.7 on 2019-02-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping_app', '0008_auto_20190226_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='detail',
            new_name='price',
        ),
    ]
